name: Upload and Notify

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: [self-hosted, windows]

    steps:

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-sync
          path: E:\data\aliyun\data\
          retention-days: 1

      - name: Get latest artifact id
        id: get_id
        shell: powershell
        run: |
          $repo = "<liudongdongdong7397/<aliyun_docker_sync>"
          $headers = @{
            Authorization = "Bearer ${{ secrets.PAT_A_TO_B }}"
            Accept        = "application/vnd.github+json"
          }

          $api = "https://api.github.com/repos/$repo/actions/artifacts"
          $response = Invoke-RestMethod -Uri $api -Headers $headers
          $id = $response.artifacts[0].id

          Write-Output "ART_ID=$id" >> $env:GITHUB_OUTPUT

      - name: Dispatch Repo-B
        shell: powershell
        run: |
          $repoB = "<liushiyou006>/<aliyun_sync>"
          $headers = @{
            Authorization = "Bearer ${{ secrets.PAT_A_TO_B }}"
            Accept        = "application/vnd.github+json"
          }

          $body = @{
            event_type = "sync_event"
            client_payload = @{
              artifact_id = "${{ steps.get_id.outputs.ART_ID }}"
            }
          } | ConvertTo-Json -Depth 3

          Invoke-RestMethod `
            -Method Post `
            -Uri "https://api.github.com/repos/$repoB/dispatches" `
            -Headers $headers `
            -Body $body

      - name: Clear folder
        shell: powershell
        run: |
          Remove-Item C:\sync_folder\* -Force
